/* PostgreSQL bootstrap DDL — shared by the runtime (src/db/index.ts) and the
   PGlite smoke test (scripts/smoke-pglite.ts). */
export const BOOTSTRAP = `
CREATE TABLE IF NOT EXISTS organization (
  id INTEGER PRIMARY KEY, name TEXT NOT NULL, short TEXT NOT NULL,
  tagline TEXT NOT NULL DEFAULT '', region TEXT NOT NULL DEFAULT '',
  accent TEXT NOT NULL DEFAULT '#D14124', logo_mode TEXT NOT NULL DEFAULT 'calv',
  logo_data TEXT, fy_start TEXT NOT NULL DEFAULT 'October',
  csbg_ceiling INTEGER NOT NULL DEFAULT 125
);
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY, name TEXT NOT NULL, username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL, role TEXT NOT NULL,
  access TEXT NOT NULL DEFAULT 'assigned', initials TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS user_programs (
  user_id TEXT NOT NULL, program_id TEXT NOT NULL,
  PRIMARY KEY (user_id, program_id)
);
CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY, user_id TEXT NOT NULL, expires_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS programs (
  id TEXT PRIMARY KEY, name TEXT NOT NULL, short TEXT NOT NULL, color TEXT NOT NULL,
  type TEXT NOT NULL, sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  fpl_ceiling INTEGER, sort INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS doc_types (key TEXT PRIMARY KEY, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS program_docs (
  program_id TEXT NOT NULL, doc_key TEXT NOT NULL,
  PRIMARY KEY (program_id, doc_key)
);
CREATE TABLE IF NOT EXISTS clients (
  id TEXT PRIMARY KEY, first TEXT NOT NULL, last TEXT NOT NULL, dob TEXT NOT NULL,
  sex TEXT, race TEXT, edu TEXT, work TEXT, insurance TEXT, military TEXT,
  disability INTEGER, phone TEXT, address TEXT, county TEXT, hh_type TEXT,
  hh_size INTEGER NOT NULL DEFAULT 1, housing TEXT,
  income INTEGER NOT NULL DEFAULT 0, income_src TEXT, caseworker_id TEXT,
  enrolled TEXT NOT NULL, fpl_year INTEGER NOT NULL, next_follow_up TEXT,
  flags JSONB NOT NULL DEFAULT '[]'::jsonb, custom JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS client_programs (
  client_id TEXT NOT NULL, program_id TEXT NOT NULL,
  PRIMARY KEY (client_id, program_id)
);
CREATE TABLE IF NOT EXISTS applications (
  id TEXT PRIMARY KEY, first TEXT NOT NULL, last TEXT NOT NULL, dob TEXT NOT NULL,
  phone TEXT, address TEXT, county TEXT, sex TEXT, race TEXT, edu TEXT, work TEXT,
  insurance TEXT, military TEXT, disability INTEGER, hh_type TEXT,
  hh_size INTEGER NOT NULL DEFAULT 1, housing TEXT,
  income INTEGER NOT NULL DEFAULT 0, income_src TEXT,
  custom JSONB NOT NULL DEFAULT '{}'::jsonb,
  program_id TEXT NOT NULL, caseworker_id TEXT,
  stage TEXT NOT NULL DEFAULT 'docs', applied TEXT NOT NULL,
  fpl_year INTEGER NOT NULL, notes TEXT NOT NULL DEFAULT '',
  decision_note TEXT, decided_by TEXT, decided_at TEXT, client_id TEXT,
  portal_token TEXT UNIQUE
);
CREATE TABLE IF NOT EXISTS application_docs (
  application_id TEXT NOT NULL, doc_key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'missing', source TEXT, updated_at TEXT,
  file_name TEXT, file_path TEXT, file_by TEXT, file_at TEXT,
  verified_by TEXT, verified_at TEXT,
  bypass_by TEXT, bypass_at TEXT, bypass_reason TEXT,
  PRIMARY KEY (application_id, doc_key)
);
CREATE TABLE IF NOT EXISTS services (
  code TEXT PRIMARY KEY, domain TEXT NOT NULL, label TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1, sort INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS program_services (
  program_id TEXT NOT NULL, code TEXT NOT NULL,
  PRIMARY KEY (program_id, code)
);
CREATE TABLE IF NOT EXISTS service_log (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date TEXT NOT NULL, client_id TEXT NOT NULL,
  code TEXT NOT NULL, program_id TEXT NOT NULL, staff_id TEXT NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  file_name TEXT, file_path TEXT
);
CREATE TABLE IF NOT EXISTS fpl_schedules (
  year INTEGER PRIMARY KEY, base INTEGER NOT NULL, per_additional INTEGER NOT NULL,
  effective TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'archived'
);
CREATE TABLE IF NOT EXISTS lists (key TEXT PRIMARY KEY, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS list_values (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  list_key TEXT NOT NULL,
  value TEXT NOT NULL, sort INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS intake_fields (
  id TEXT PRIMARY KEY, label TEXT NOT NULL, code TEXT NOT NULL DEFAULT '',
  type TEXT NOT NULL, list_key TEXT, options_text TEXT,
  enabled INTEGER NOT NULL DEFAULT 1, builtin INTEGER NOT NULL DEFAULT 0,
  sort INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS fnpi_progress (
  code TEXT PRIMARY KEY, label TEXT NOT NULL,
  served INTEGER NOT NULL DEFAULT 0, target INTEGER NOT NULL DEFAULT 0,
  actual INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS outcome_log (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date TEXT NOT NULL, client_id TEXT NOT NULL,
  code TEXT NOT NULL, program_id TEXT NOT NULL, staff_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'achieved', note TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS integrations (
  id TEXT PRIMARY KEY, name TEXT NOT NULL, kind TEXT NOT NULL, status TEXT NOT NULL,
  last_sync TEXT NOT NULL DEFAULT '', records TEXT NOT NULL DEFAULT '',
  detail TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS import_jobs (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  at TEXT NOT NULL, template TEXT NOT NULL,
  filename TEXT NOT NULL, imported INTEGER NOT NULL DEFAULT 0,
  updated INTEGER NOT NULL DEFAULT 0, skipped INTEGER NOT NULL DEFAULT 0,
  staff_id TEXT NOT NULL, detail TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS audit_log (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  at TEXT NOT NULL, user_id TEXT,
  action TEXT NOT NULL, entity TEXT NOT NULL, entity_id TEXT NOT NULL,
  detail TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS kv (key TEXT PRIMARY KEY, value JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS classes (
  id TEXT PRIMARY KEY, program_id TEXT NOT NULL, name TEXT NOT NULL,
  site TEXT NOT NULL DEFAULT '', schedule TEXT NOT NULL DEFAULT '',
  srv_code TEXT NOT NULL DEFAULT 'SRV 2h'
);
CREATE TABLE IF NOT EXISTS students (
  id TEXT PRIMARY KEY, class_id TEXT NOT NULL, name TEXT NOT NULL, client_id TEXT,
  grade TEXT NOT NULL DEFAULT '', school TEXT NOT NULL DEFAULT '',
  term_pct INTEGER NOT NULL DEFAULT 100
);
CREATE TABLE IF NOT EXISTS class_sessions (
  id TEXT PRIMARY KEY, class_id TEXT NOT NULL, date TEXT NOT NULL,
  label TEXT NOT NULL, posted INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS attendance_marks (
  session_id TEXT NOT NULL, student_id TEXT NOT NULL, mark TEXT,
  PRIMARY KEY (session_id, student_id)
);
CREATE TABLE IF NOT EXISTS contractors (
  id TEXT PRIMARY KEY, program_id TEXT NOT NULL, name TEXT NOT NULL,
  trade TEXT NOT NULL DEFAULT '', crews INTEGER NOT NULL DEFAULT 1,
  phone TEXT NOT NULL DEFAULT '', insurance_exp TEXT NOT NULL,
  bpi_exp TEXT NOT NULL, epa_rrp_exp TEXT NOT NULL,
  qc_pass INTEGER NOT NULL DEFAULT 100
);
CREATE TABLE IF NOT EXISTS wx_jobs (
  id TEXT PRIMARY KEY, program_id TEXT NOT NULL, client_name TEXT NOT NULL,
  client_id TEXT, address TEXT NOT NULL DEFAULT '',
  stage TEXT NOT NULL DEFAULT 'audit', contractor_id TEXT,
  funding TEXT NOT NULL DEFAULT '', measures TEXT NOT NULL DEFAULT '',
  started TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS pantry_agencies (
  id TEXT PRIMARY KEY, program_id TEXT NOT NULL, name TEXT NOT NULL,
  town TEXT NOT NULL DEFAULT '', county TEXT NOT NULL DEFAULT '',
  contact TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT '',
  compliance TEXT NOT NULL DEFAULT 'current'
);
CREATE TABLE IF NOT EXISTS pantry_reports (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id TEXT NOT NULL, month TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'missing', households INTEGER, lbs INTEGER
);
CREATE TABLE IF NOT EXISTS seminars (
  id TEXT PRIMARY KEY, program_id TEXT NOT NULL, title TEXT NOT NULL,
  date TEXT NOT NULL, time TEXT NOT NULL DEFAULT '', site TEXT NOT NULL DEFAULT '',
  capacity INTEGER NOT NULL DEFAULT 0, registered INTEGER NOT NULL DEFAULT 0,
  srv_code TEXT NOT NULL DEFAULT 'SRV 3a'
);
CREATE TABLE IF NOT EXISTS seminar_attendees (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  seminar_id TEXT NOT NULL, name TEXT NOT NULL,
  client_id TEXT, application_id TEXT,
  intake_status TEXT NOT NULL DEFAULT 'not-started'
);
CREATE TABLE IF NOT EXISTS projects (
  id TEXT PRIMARY KEY, program_id TEXT NOT NULL, name TEXT NOT NULL,
  town TEXT NOT NULL DEFAULT '', buyer TEXT NOT NULL DEFAULT '',
  budget INTEGER NOT NULL DEFAULT 0, spent INTEGER NOT NULL DEFAULT 0,
  pct INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS project_milestones (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  project_id TEXT NOT NULL, label TEXT NOT NULL,
  done INTEGER NOT NULL DEFAULT 0, current INTEGER NOT NULL DEFAULT 0,
  sort INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS project_requirements (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  project_id TEXT NOT NULL, label TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'current'
);
CREATE TABLE IF NOT EXISTS volunteers (
  id TEXT PRIMARY KEY, name TEXT NOT NULL, client_id TEXT,
  low_income INTEGER NOT NULL DEFAULT 0, role TEXT NOT NULL DEFAULT '',
  hours_fy INTEGER NOT NULL DEFAULT 0, last_shift TEXT
);
CREATE TABLE IF NOT EXISTS volunteer_programs (
  volunteer_id TEXT NOT NULL, program_id TEXT NOT NULL,
  PRIMARY KEY (volunteer_id, program_id)
);
CREATE TABLE IF NOT EXISTS loans (
  id TEXT PRIMARY KEY, program_id TEXT NOT NULL, borrower TEXT NOT NULL,
  client_id TEXT, purpose TEXT NOT NULL DEFAULT '',
  principal INTEGER NOT NULL DEFAULT 0, balance INTEGER NOT NULL DEFAULT 0,
  rate TEXT NOT NULL DEFAULT '', term TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'current', next_due TEXT,
  srv_code TEXT NOT NULL DEFAULT 'SRV 3b'
);
CREATE INDEX IF NOT EXISTS idx_service_log_client ON service_log (client_id);
CREATE INDEX IF NOT EXISTS idx_service_log_program ON service_log (program_id);
CREATE INDEX IF NOT EXISTS idx_outcome_log_client ON outcome_log (client_id);
CREATE INDEX IF NOT EXISTS idx_outcome_log_code ON outcome_log (code);
CREATE INDEX IF NOT EXISTS idx_client_programs_program ON client_programs (program_id);
CREATE INDEX IF NOT EXISTS idx_applications_stage ON applications (stage);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_log (entity, entity_id);
-- Columns added after a table first shipped (CREATE TABLE IF NOT EXISTS won't add
-- them to an existing database) — Postgres supports ADD COLUMN IF NOT EXISTS.
ALTER TABLE application_docs ADD COLUMN IF NOT EXISTS file_name TEXT;
ALTER TABLE application_docs ADD COLUMN IF NOT EXISTS file_path TEXT;
ALTER TABLE application_docs ADD COLUMN IF NOT EXISTS file_by TEXT;
ALTER TABLE application_docs ADD COLUMN IF NOT EXISTS file_at TEXT;
ALTER TABLE application_docs ADD COLUMN IF NOT EXISTS verified_by TEXT;
ALTER TABLE application_docs ADD COLUMN IF NOT EXISTS verified_at TEXT;
ALTER TABLE application_docs ADD COLUMN IF NOT EXISTS bypass_by TEXT;
ALTER TABLE application_docs ADD COLUMN IF NOT EXISTS bypass_at TEXT;
ALTER TABLE application_docs ADD COLUMN IF NOT EXISTS bypass_reason TEXT;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS fpl_ceiling INTEGER;
ALTER TABLE service_log ADD COLUMN IF NOT EXISTS file_name TEXT;
ALTER TABLE service_log ADD COLUMN IF NOT EXISTS file_path TEXT;
-- Phase 2 (AR 3.0 compliance core): jurisdictioned FPL, income worksheet,
-- frozen determinations, state income-lookback policy.
ALTER TABLE organization ADD COLUMN IF NOT EXISTS jurisdiction TEXT NOT NULL DEFAULT 'contiguous48';
ALTER TABLE organization ADD COLUMN IF NOT EXISTS income_lookback_days INTEGER NOT NULL DEFAULT 90;
ALTER TABLE fpl_schedules ADD COLUMN IF NOT EXISTS jurisdiction TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS income_worksheet JSONB;
ALTER TABLE applications ADD COLUMN IF NOT EXISTS income_worksheet JSONB;
ALTER TABLE applications ADD COLUMN IF NOT EXISTS determination JSONB;
ALTER TABLE organization ADD COLUMN IF NOT EXISTS contact_line TEXT NOT NULL DEFAULT '';
-- TOTP MFA + session metadata
ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_secret TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS recovery_codes JSONB NOT NULL DEFAULT '[]';
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS mfa_pending INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS created_at TEXT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS user_agent TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locale TEXT NOT NULL DEFAULT 'en';
-- Phase 4: ROMA agency goals (Org Standard 4.3)
CREATE TABLE IF NOT EXISTS roma_goals (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '',
  fnpi_codes JSONB NOT NULL DEFAULT '[]', sort INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);
`;
